### PR TITLE
Lineage 18.1

### PR DESCRIPTION
**Pull request by Ten-Shine**

### CODE REVIEW

**Comment by Golv** [comment]
Hi!
Did you manage to run dot11 or Havoc11?

**Comment by Ten-Shine** [comment]
> Hi!
> Did you manage to run dot11 or Havoc11?

Yes. And I have built Bliss successfully. But something  is wrong. I think the reason is [bliss kill lineage-sdk ](https://github.com/BlissRoms/platform_manifest/commit/fb81674188a6086ab62d89421467c2ce8be376a7).

Now I upload CrDroid , RROS-Q, wrong Bliss to MEGA to you.

**Comment by Ten-Shine** [comment]
> Hi!
> Did you manage to run dot11 or Havoc11?

https://mega.nz/folder/zIESlZCY#vrWJTkH5IlzbJhiPWt3Qbw

**Comment by Golv** [comment]
Let me know when you manage to build any rom suitable for daily use.

**Comment by Ten-Shine** [comment]
Now I think CrDroid is suitable for daily use. 
I build CrDroid by your device tree without any change. And it work well expect WIFI. Sometimes WIFI is failed to connect. I don't know why. It makes few influences in total.

I decide to give Havoc and Bliss up because of some bugs. And I have no time to fix them.
I have not built DotOS.
When I am free , I will try EvolutionX.

**Pull request merged**
